export const videos = [
  {
    _id: "nd7hdNyK7cE",
    title: "The Ashes Day 4 2023 |  Highlights  ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://yt3.googleusercontent.com/fRTh6Q0FUUZ50HFjtiUw_5DeDhQy87dhpUOdLzPySHsZXipNu3lpD4R9oxyKUzXY_DDUVPZB=s176-c-k-c0x00ffffff-no-rj",
    img: "https://i.ytimg.com/vi/nd7hdNyK7cE/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDnTCwKJkSUJm1qNw9ZHNehU7Ck4g",
  },
  {
    _id: "fbO_0AbkUOg",
    title: "Barcelona vs Real Madrid 1-3  ",
    creator: "Football",
    category: "Football",
    logo: "https://yt3.googleusercontent.com/fRTh6Q0FUUZ50HFjtiUw_5DeDhQy87dhpUOdLzPySHsZXipNu3lpD4R9oxyKUzXY_DDUVPZB=s176-c-k-c0x00ffffff-no-rj",
    img: "https://i.ytimg.com/vi/NuG1ci3CNUc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAFzPciL_pYnApCOLZs0pQbsm9yZw",
  },
  {
    _id: "qQQcepP3ctQ",
    title: "FIH Hockey Pro League ",
    creator: "Hockey",
    category: "Hockey",
    logo: "https://i.ytimg.com/vi/qQQcepP3ctQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPd1LSyW3-DMolnuutjuEe74kGHA",
    img: "https://i.ytimg.com/vi/qQQcepP3ctQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPd1LSyW3-DMolnuutjuEe74kGHA",
  },
  {
    _id: "I5EcnXH0Ntc",
    title: "The Ashes Day 2 2023 |  Highlights ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
  },
  {
    _id: "tGXis5ZVH40",
    title: "India 2-0 Lebanon Final",
    creator: "Football",
    category: "Football",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/tGXis5ZVH40/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDGZuV7qXi9ipBvYx2ubTC-7y4hdA",
  },
  {
    _id: "lqqbdBnpAdY",
    title: "Hockey  Argentina v India ",
    creator: "Hockey",
    category: "Hockey",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/lqqbdBnpAdY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLALL6HDYYwKcfOzI6P5H1Z_NC-bfw",
  },
  {
    _id: "dYFG8mOoYfY",
    title: "England Bowled 183 |  Highlights ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/dYFG8mOoYfY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZp6BpbtYFM9b9Wuqa58u-cEgqaQ",
  },
  {
    _id: "3vO_4N7RlgY",
    title: "Hockey  India vs Belgium  ",
    creator: "Hockey",
    category: "Hockey",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/3vO_4N7RlgY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB5s2rzH8NTfcKR42a4Hm28VcIXVQ",
  },
  {
    _id: "TcBjAQXZahg",
    title: "Hockey Great Britain vs India",
    creator: "Hockey",
    category: "Hockey",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/TcBjAQXZahg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDs_KVosA3PTiVaPvHLSfR71Gm_lA",
  },
  {
    _id: "9PET9RYAY8k",
    title: "Highlights | Pakistan vs England | T20I ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/9PET9RYAY8k/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLActvjhRq6WstsDQjIe0ULcsBJ-kw",
  },
  {
    _id: "tGXis5ZVH40",
    title: "India 2-0 Lebanon Final",
    creator: "Football",
    category: "Football",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/tGXis5ZVH40/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDGZuV7qXi9ipBvYx2ubTC-7y4hdA",
  },
  {
    _id: "vvuAReoU0WQ",
    title: "Highlights | South Africa vs Pakistan  ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/vvuAReoU0WQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAMKFJdZAq3Qh-tIKr3_xyKj5X4wg",
  },
  {
    _id: "8iXHBo_c0YA",
    title: "Highlights - England v India ODI",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/8iXHBo_c0YA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBtz0MT3Eils-xr2nypVzaBbfsQ0w",
  },
  {
    _id: "90DbbceNqF0",
    title: "Manchester City 1 - 0 Inter Milan ",
    creator: "Football",
    category: "Football",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/90DbbceNqF0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCejIjBDm-jYn7qss2fKid5Fynhqw",
  },
  {
    _id: "TFy6ldA4-Xs",
    title: "WI v IND | 3rd T20I highlights ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/TFy6ldA4-Xs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnintP7W5BWP4XL016kGqV7cQsEQ",
  },
  {
    _id: "c3rZsfQkQkM",
    title: "Netherlands v India | highlights",
    category: "Hockey",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/c3rZsfQkQkM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEGdtIZ_jRppm3uua9b7Oe8lIwLQ",
  },
  {
    _id: "KVI2gvZCVrQ",
    title: "FINAL Match | ARG 3:3 FRA",
    creator: "Football",
    category: "Football",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/KVI2gvZCVrQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDAY7A_AAPkEv6p-OgFeDIHc6C2lA",
  },
  {
    _id: "We74qn8U3c0",
    title: "Highlights | Pakistan vs South Africa",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/We74qn8U3c0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBcA7sDl7n6UWEY45axum_0SLJJyw",
  },
  {
    _id: "1s0-0H4yW-w",
    title: "India v Pakistan | Men's Hockey ",
    creator: "Hockey",
    category: "Hockey",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/1s0-0H4yW-w/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnt_sFtUEP9eEHZcSjJa_SMJPvIA",
  },
  {
    _id: "AFEZzf9_EHk",
    title: "India v Pakistan - Match Highlights ",
    creator: "Cricket",
    category: "Cricket",
    logo: "https://i.ytimg.com/vi/I5EcnXH0Ntc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2hXZ2B0EezW5hgE9uIP9Qv4Nbzg",
    img: "https://i.ytimg.com/vi/AFEZzf9_EHk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBBei3ssGKvwotbtHY1VZVTGF5GNg",
  },
];
